biblioteka/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
     path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/urls.py
from django.urls import path
from . import views
from django.urls import include, re_path

urlpatterns = [
	path('', views.index, name='index'),
	re_path(r'^ksiazki/$', views.KsiazkaListView.as_view(), name='ksiazki'),
	re_path(r'^ksiazka/(?P<pk>\d+)$', views.KsiazkaDetailView.as_view(), name='szczegoly_ksiazki'),
	re_path(r'^autorzy/$', views.AutorzyListView.as_view(), name='autorzy'),
	re_path(r'^autor/(?P<pk>\d+)$', views.AutorDetailView.as_view(), name='szczegoly_o_autorze'),
]

urlpatterns += [
    re_path(r'^pozyczone/$', views.LoanedBooksByUserListView.as_view(), name='pozyczone'),
    re_path(r'^wszystkie/$', views.LoanedBooksAllListView.as_view(), name='wszystkie')
]

urlpatterns += [
    re_path(r'^ksiazka/(?P<pk>[-\w]+)/renew/$', views.przedluzenie, name='przedluzenie'),
    re_path(r'^autor/dodanie_autora$', views.dodanie_autora, name='dodanie_autora'),
    re_path(r'^ksiazka/dodanie_ksiazki$', views.dodanie_ksiazki, name='dodanie_ksiazki'),
    re_path(r'^administrowanie$', views.administrowanie, name='administrowanie')
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

from django.db.models.signals import post_save
from django.dispatch import receiver

from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.


class Gatunek(models.Model):
    nazwa = models.CharField(max_length=127, help_text="Wpisz gatunek książki")

    def __str__(self):
        return self.nazwa

class Ksiazka(models.Model):
    tytul = models.CharField(max_length=127)
    autor = models.ForeignKey('Autor', on_delete=models.SET_NULL, null=True)
    opis = models.TextField(max_length=4095, help_text="Wpisz krótki opis książki", blank=True)
    isbn = models.CharField('ISBN',max_length=13, help_text='<a href="https://www.isbn-international.org">Numer ISBN</a>')
    gatunek = models.ManyToManyField(Gatunek, help_text="Wybierz gatunek książki")
    obraz = models.CharField(max_length=255, null=True, blank=True, help_text="Wpisz link do obrazu")

    def __str__(self):
        return self.tytul

    def get_absolute_url(self):
        return reverse('szczegoly_ksiazki', args=[str(self.id)])

    def gatunki(self):
        return ', '.join([ gatunek.nazwa for gatunek in self.gatunek.all()[:3] ])
    gatunki.skrot = 'Gatunek'

class Egzemplarz(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unikalny ID dla konkretnego egzemplarza książki")
    ksiazka = models.ForeignKey('Ksiazka', on_delete=models.SET_NULL, null=True)
    wydawca = models.CharField(max_length=127)
    zwrot = models.DateField(null=True, blank=True)
    odbiorca = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS = (('k', 'Konserwacja'), ('w', 'Wypożyczona'), ('d', 'Dostępna'), ('z', 'Zarezerwowana'),)
 
    status = models.CharField(max_length=1, choices=STATUS, blank=True, default='k', help_text='Dostępność książki')

    class Meta:
        ordering = ["zwrot"]
        permissions = (("can_mark_returned", "Set book as returned"),)

    @property
    def zalegly(self):
        if self.zwrot and date.today() > self.zwrot:
            return True
        return False


    def __str__(self):
        return '%s (%s)' % (self.id,self.ksiazka.tytul)

class Autor(models.Model):
    imie = models.CharField(max_length=127)
    nazwisko = models.CharField(max_length=127)
    data_urodzenia = models.DateField(null=True, blank=True)
    data_smierci = models.DateField(null=True, blank=True)
    zdiecie = models.CharField(max_length=255, null=True, blank=True, help_text="Wpisz link do zdięcia")
    zyciorys = models.TextField(max_length=2047, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('szczegoly_o_autorze', args=[str(self.id)])


    def __str__(self):
        return '%s, %s' % (self.nazwisko, self.imie)

catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime


class Przedluzenie(forms.Form):
    odswiezona_data = forms.DateField(help_text="Wpisz datę pomiędzy teraz i 4 tygodni do przodu")

    def formatowanie(self):
        data = self.cleaned_data['odswiezona_data']

        if data < datetime.date.today():
            raise ValidationError(_('Zła data - nie wolno zmienić na przyszłą datę'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Zła data - przedłużenie więcej niż na 4 tygodnie'))

        return data

class DodanieAutora(forms.Form):
    imie = forms.CharField(help_text="Wpisz imię autora")
    nazwisko = forms.CharField(help_text="Wpisz nazwisko autora")

    def formatowanie(self):
        dane = self.cleaned_data
        return imie, nazwisko

class DodanieKsiazki(forms.Form):
    tytul = forms.CharField(help_text="Wpisz tytuł")
    isbn = forms.CharField(help_text="Wpisz numer ISBN")
    def formatowanie(self):
        dane = self.cleaned_data
        return dane

catalog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Ksiazka, Autor, Egzemplarz, Gatunek
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
# from django.http import HttpResponse
from django.contrib.auth.decorators import permission_required
from django.utils.translation import gettext_lazy as _
from django.shortcuts import get_object_or_404

from django.http import HttpResponseRedirect
from django.urls import reverse

import datetime
from django import forms
from .forms import Przedluzenie, DodanieAutora, DodanieKsiazki
from django.db import models



from django.views.generic.edit import CreateView, UpdateView, DeleteView

def index(request):
    ilosc_ksiazek = Ksiazka.objects.all().count()
    ilosc_egzemplarzy = Egzemplarz.objects.all().count()
    ilosc_dostepnych_egzemplarzy = Egzemplarz.objects.filter(status__exact='d').count()
    ilosc_autorow = Autor.objects.count()
    ilosc_gatunkow = Gatunek.objects.count()


    context = {
        'ilosc_ksiazek': ilosc_ksiazek,
        'ilosc_egzemplarzy': ilosc_egzemplarzy,
        'ilosc_dostepnych_egzemplarzy': ilosc_dostepnych_egzemplarzy,
        'ilosc_autorow': ilosc_autorow,
        'ilosc_gatunkow': ilosc_gatunkow,
    }

    return render(request, 'index.html', context=context)

class KsiazkaListView(generic.ListView):
    model = Ksiazka
    template_name = 'catalog/lista_ksiazek.html'
    paginate_by = 8
    ordering =['tytul']


class KsiazkaDetailView(generic.DetailView):
    model = Ksiazka
    template_name = 'catalog/szczegoly_ksiazki.html'
    
    def post(self, request, *args,**kwargs):
        if request.method == 'POST' :
            ksiazka = Ksiazka.objects.get(pk=self.kwargs.get('pk'))

            wybor_wydawcy = request.POST.get('wybor_wydawcy')
            
            egzem = Egzemplarz.objects.get(id=wybor_wydawcy)
            uzytk = request.user

            if uzytk.egzemplarz_set.count() < 3:

                if egzem.status == 'z' and egzem.odbiorca == uzytk:
                    egzem.status = 'd'
                    egzem.odbiorca = None
                        
                elif egzem.status == 'd':
                    egzem.status = 'z'
                    egzem.odbiorca = uzytk
                
            egzem.save()
        return render(request, self.template_name, context={'ksiazka': ksiazka})

class AutorzyListView(generic.ListView):
    model = Autor
    template_name = 'catalog/lista_autorow.html'

    ordering =['imie']

class AutorDetailView(generic.DetailView):
    model = Autor
    template_name = 'catalog/szczegoly_o_autorze.html'

class RedirectLogin(LoginRequiredMixin, generic.View):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = Egzemplarz
    template_name = 'catalog/lista_pozyczonych_egzemplarzy.html'
    paginate_by = 10

    def get_queryset(self):
        return Egzemplarz.objects.filter(odbiorca=self.request.user).filter(status__exact='w').order_by('zwrot')

class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    model = Egzemplarz
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/lista_wszystkich_pozyczonych_egzemplarzy.html'
    paginate_by = 10
    
    def get_queryset(self):
        return Egzemplarz.objects.filter(status__exact='w').order_by('zwrot')


@permission_required('catalog.can_mark_returned')
def dodanie_autora(request):
    if request.method == 'POST':
        form = DodanieAutora(request.POST)

        if form.is_valid():
            autor = Autor(imie=form.cleaned_data['imie'], nazwisko=form.cleaned_data['nazwisko'])
            autor.save()

            return HttpResponseRedirect(reverse('index'))
    else: form = DodanieAutora()

    return render(request, 'catalog/autor_form.html', {'form': form})


def dodanie_ksiazki(request):
    model = Autor.objects.all()

    if request.method == 'POST':
        form = DodanieKsiazki(request.POST)

        wybor_autora = request.POST.get('wybor_autora')
        autor = Autor.objects.get(id=wybor_autora)

        if form.is_valid():
            ksiazka = Ksiazka(tytul=form.cleaned_data['tytul'], isbn=form.cleaned_data['isbn'], autor=autor)
            ksiazka.save()

    else: form = DodanieKsiazki()
    return render(request, 'catalog/ksiazka_form.html', {'form': form, 'lista_autorow': model})

def administrowanie(request):

    return render(request, 'catalog/administrowanie.html')

def przedluzenie(request, pk):
    egzempl = get_object_or_404(Egzemplarz, pk=pk)

    if request.method == 'POST':

        form = Przedluzenie(request.POST)

        # Проверка валидности данных формы:
        if form.is_valid():

            egzempl.zwrot = form.cleaned_data['odswiezona_data']
            egzempl.save()

            return HttpResponseRedirect(reverse('wszystkie') )

    else:
        proponowana_odswiezona_data = datetime.date.today() + datetime.timedelta(weeks=3)
        form = Przedluzenie(initial={'odswiezona_data': proponowana_odswiezona_data,})

    return render(request, 'catalog/przedluzenie.html', {'form': form, 'egzempl':egzempl})

catalog/templates/catalog/administrowanie.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

<div class="container">
	<h1>Administrowanie</h1>
	<div class="icon__items">
		<div class="icons">
			<a href="{% url 'dodanie_autora' %}" title="">
				<img src="{% static 'icons/user.png' %}" alt="" width="100px"></a>
			<a href="{% url 'dodanie_autora' %}" title="">Dodanie autora</a>
		</div>

		<div class="icons">
			<a href="{% url 'dodanie_ksiazki' %}" title="">
				<img src="{% static 'icons/book_plus.png' %}" alt="" width="100px"></a>
			<a href="{% url 'dodanie_ksiazki' %}" title="">Dodanie ksiazki</a>
		</div>

		<div class="icons">
			<a href="{% url 'wszystkie' %}" title="">
				<img src="{% static 'icons/search.png' %}" alt="" width="100px"></a>
			<a href="{% url 'wszystkie' %}" title="">Lista wszystkich wypożyczonych książek</a>
		</div>
	</div>
	
</div>

{% endblock %}

catalog/templates/catalog/autor_form.html
{% extends "base_generic.html" %}
{% block content %}

<div class="container">    
	<h1>Dodanie autora</h1>
	<form class="add" action="" method="post">

        {% csrf_token %}
        {{ form }}
        <div class="submit">
            <input type="submit" value="Zapisz" />
        </div>
    </form>
</div>

{% endblock %}

catalog/templates/catalog/ksiazka_form.html
{% extends "base_generic.html" %}
{% block content %}

<div class="container">
    <h1>Dodanie książki</h1>
    <form class="add" action="" method="post">

        {% csrf_token %}
            {{ form }}
        {% if lista_autorow %}

        
        <select name="wybor_autora">
            {% for autor in lista_autorow %}
                <option value=" {{autor.id}} ">{{ autor.imie }} {{ autor.nazwisko }}</option>
            {% endfor %}
        </select>
        {% endif %}
        <div class="submit">
            <input type="submit" value="Zapisz" />
        </div>
        
    </form>
</div>

{% endblock %}

catalog/templates/catalog/lista_autorow.html
{% extends "base_generic.html" %}
{% block content %}

<div class="container">

  <h1>Lista autorów</h1>

    {% if autor_list %}
    <ul class="square">
      {% for autor in autor_list %}
      <li>
        <a href="{{ autor.get_absolute_url }}">{{ autor.imie }} {{ autor.nazwisko }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Nie ma autorów na liście</p>
    {% endif %} 
  
</div>
    
{% endblock %}

catalog/templates/catalog/lista_ksiazek.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}

    <div class="container">
      <h1 class="book__header">Lista książek</h1>

      <div class="books__list">
        {% if ksiazka_list %}
          {% for ksiazka in ksiazka_list %}

            <div class="book__item">
              <div class="book__picture">
                {% static 'ksiazki/' as obrazy %}
                <a href="{{ ksiazka.get_absolute_url }}"><img src="{{obrazy}}/{{ksiazka.obraz}}" alt=""></a>
              </div>
              
              <div class="book__title">
                <a href="{{ ksiazka.get_absolute_url }}">{{ ksiazka.tytul }}</a> <br>({{ksiazka.autor}})
              </div>
            </div>

          {% endfor %}
        {% else %}

          <p>Nie ma książek w bibliotece</p>

        {% endif %}
      </div>

      {% if is_paginated %}
      <div>
          <span>
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">poprzednia</a>
              {% endif %}
              <span>
                  Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">następna</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
    
    </div>

    
    
{% endblock %}

catalog/templates/catalog/lista_pozyczonych_egzemplarzy.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
      
    <h1>Pożyczone księgi</h1>

    {% if egzemplarz_list %}
    <ul>

      {% for egzempl in egzemplarz_list %}
      <li>
        <a href="{% url 'szczegoly_ksiazki' egzempl.ksiazka.pk %}">{{egzempl.ksiazka.tytul}}</a> ({{ egzempl.zwrot }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Nie ma pożyczonych książek</p>
    {% endif %}

    </div>
{% endblock %}

catalog/templates/catalog/lista_wszystkich_pozyczonych_egzemplarzy.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
      
    <h1>Wszystkie pożyczone egzemplarze</h1>
    
    
    {% if egzemplarz_list %}
    <ul>

      {% for egzempl in egzemplarz_list %} 
      <li>
        <a href="{% url 'szczegoly_ksiazki' egzempl.ksiazka.pk %}">
        {{egzempl.ksiazka.tytul}}
      </a> 
      ({{ egzempl.zwrot }}) {% if user.is_staff %}- {{ egzempl.odbiorca }}{% endif %}
      {% if perms.catalog.can_mark_returned %} - <a href="{% url 'przedluzenie' egzempl.id %}">Przedłużenie</a>{% endif %}
      </li>
      {% endfor %}
      
    </ul>

    {% else %}
      <p>Nie ma pożyczonych książek</p>
    {% endif %}

    </div>
           
{% endblock %}

catalog/templates/catalog/przedluzenie.html
{% extends "base_generic.html" %}
{% block content %}
<div class="container">
    <h1>Przedłużenie: {{egzempl.ksiazka.tytul}}</h1>
    <p>Odbiorca: {{egzempl.odbiorca}}</p>
    <p>Termin: {{egzempl.zwrot}}</p>

    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Zapisz" />
    </form>
</div>
    

{% endblock %}

catalog/templates/catalog/szczegoly_ksiazki.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
<div class="container">
  <div class="book__detail">

    <div class="book__detail__picture">
      {% static 'ksiazki/' as obrazy %}
      <img src = "{{obrazy}}/{{ksiazka.obraz}}" alt="">
    </div>
          

      <div class="book__detail__text">
        <h1><b> {{ ksiazka.tytul }} </b></h1>

          <p><b>Autor:</b> <a href="{% url 'szczegoly_o_autorze' ksiazka.autor.pk %}">{{ ksiazka.autor }}</a></p>
          <p><b>Opis:</b> {{ ksiazka.opis|linebreaksbr }}</p>
          <p><b>ISBN:</b> {{ ksiazka.isbn }}</p>
          <p><b>Gatunek:</b> {% for gatunek in ksiazka.gatunek.all %} {{ gatunek }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
          </div>
        </div>

  <div>
    <form method="post">
      {% csrf_token %}
      {% if ksiazka.egzemplarz_set.all %}
      <select name = "wybor_wydawcy">
            {% for copy in ksiazka.egzemplarz_set.all %}
              <option value="{{copy.id}}">{{copy.wydawca}} {{ copy.id|truncatechars_html:9 }}</option>
            {% endfor %}
          <input type="submit" value="Wybierz" />
        {% endif %}
      </select>
    </form>
  </div>

  <div style="margin-left:20px;margin-top:20px">
        <h4>Kopie</h4>

        {% for copy in ksiazka.egzemplarz_set.all %}
        <hr>
        <p>{{ copy.get_status_display }}</p>
        {% if copy.status != 'd' %}<p><b>Data zwrotu:</b> {{copy.zwrot}}</p>{% endif %}
        <p><b>Wydawca:</b> {{copy.wydawca}}</p>
        <p><b>Id:</b> {{copy.id}}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/szczegoly_o_autorze.html
{% extends "base_generic.html" %}
{% load static %}
{% block content %}
	<div class="container">

		<div class="autor__detail">

			<div class="autor__detail__picture">
				{% static '/autorzy' as autorzy %}
		      <img src = "{{autorzy}}/{{ autor.zdiecie }}" alt="">
				
		    </div>

		    <div class="autor__detail__text">
		    	<h1><b> {{ autor.imie }} {{ autor.nazwisko }} </b></h1>
				<p><b>Data urodzenia:</b> {{ autor.data_urodzenia }}</p>
				<p><b>Życiorys:</b> {{ autor.zyciorys|linebreaksbr }}</p>
		    </div>
		

		</div>


			<table class="rowNumbers" style="margin:10px">
				<caption>Książki</caption>
					<thead>
						<tr>
							<th>Tytuł</th>
							<th>Gatunek</th>
						</tr>
					</thead>
					<tbody>
						{% for copy in autor.ksiazka_set.all %}
						<tr>
							
						        <td >{{copy.tytul}}</td>
						        <td>{{ copy.gatunki }}</td>
						    						
						</tr>
						{% endfor %}	
					</tbody>
			</table>
		
	</div>
	

{% endblock %}